# Generated by Django 3.2.9 on 2021-11-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atv_pendente',
            field=models.TextField(default=500, max_length=200, verbose_name='Atividades pendentes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='atividades',
            field=models.IntegerField(verbose_name='Numero de Atividades dadas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='evol_aluno',
            field=models.TextField(max_length=200, verbose_name='Evolução do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='faltas',
            field=models.IntegerField(verbose_name='Faltas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='n_entregues',
            field=models.IntegerField(verbose_name='Numero de Atividades não entregues'),
        ),
    ]
